name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Build with Buildozer Docker
      uses: android-act/buildozer-action@v1
      with:
        command: |
          yes | sdkmanager --licenses || true
          buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Jarvis-APK
        path: bin/*.apk
        
